### ISSUE TITLE
Is there a way to use this lib if I override prepareForSegue:sender: ?

### ISSUE THREAD

**Issue by Ricardo1980** [patoroco/UIViewController-BlockSegue#8]
In docs I read

"IMPORTANT: if you override -prepareForSegue:sender: method, BlockSegue won't be performed in these UIViewController."

But very often we do that. Is there any way to use this lib if we override that?

**Comment by patoroco** [comment]
As you mention, in doc I specified that you need to choose between to use BlockSegue or typical performSegue: method. If you need in a specific class, you can override this method, but if you don't do that, default behaviour is try to use BlockSegue.

PD. Sorry by delay @Ricardo1980, but I forgot to answer...
